export  const FETCH_USERS_PROJECTS_ROLES_SUCCESS = 'FETCH_USERS_PROJECTS_ROLES';
export  const ADD_PROJECT_ROLE_TO_USER_SUCCESS = 'ADD_PROJECT_ROLE_TO_USER_SUCCESS';
export  const RESET_PROJECT_ROLE_USER_RESULT = 'RESET_PROJECT_ROLE_USER_RESULT';
export  const REMOVE_ROLE_FROM_PROJECT_SUCCESS = 'REMOVE_ROLE_FROM_PROJECT';
export  const RESET_REMOVE_ROLE_FROM_PROJECT = 'RESET_REMOVE_ROLE_FROM_PROJECT';
export  const ERROR_OCCURED = 'ERROR_OCCURED';

